server:
  port: 8888

spring:
  application:
    name: auth-service
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/auth-users}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASS:postgres}
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}
  rabbitmq:
    host: rabbitmq

# For testing only!
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalSeconds: 30

# creating the rabbitmq fanout exchange
exchanges:
    fanout: delete-user

queues:
    fanout: deleteUserQueue

# creating the routing key for the exchange
routing-key: key1234
