server:
  port: 8888

spring:
  application:
    name: auth-service
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  output:
    ansi:
      enabled: ALWAYS
  security:
    oauth2:
      client:
        registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}

# For testing only!
#  jpa:
#    hibernate:
#      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    leaseRenewalIntervalSeconds: 30
